library(readr)
library(readxl)
library(dplyr)
library(stringr)
base<-read_xlsx("Banco/Trabalho 3/base.xlsx")
base$estado[base$estado=="Santana Catarina"]="Santa Catarina"
base1<-base%>%select(c(sexo:dinheiro, requisitos))
base2<-base%>%select(c(jogabilidade,tempo_jogo,grafico,multiplayer,multiplayer_c, divertimento))

saveRDS(base1, "base1.rds")
saveRDS(base2,"base2.rds")

base$sexo<-base$sexo%>%as.factor()
base$escolaridade<-base$escolaridade%>%as.factor()
base$civil<-base$civil%>%as.factor()
base$estado<-base$estado%>%as.factor()
base$evento<-base$evento%>%as.factor()
base$horas_semana<-base$horas_semana%>%as.factor()
base$p_venda<-base$p_venda%>%as.factor()
base$preco_jogos<-base$preco_jogos%>%as.factor()
base$midia<-base$midia%>%as.factor()
base$requisitos<-base$requisitos%>%as.factor()
base$dinheiro<-base$dinheiro%>%as.factor()

FPS <- base$genero_jogo %>% str_detect('FPS') 
RPG <- base$genero_jogo %>% str_detect('RPG')
RTS <- base$genero_jogo %>% str_detect('RTS')
LUTA <- base$genero_jogo %>% str_detect('Luta')
ACAO <- base$genero_jogo %>% str_detect('Ação')
PUZZ <- base$genero_jogo %>% str_detect('Puzzle')
OUTROS <- base$genero_jogo %>% str_detect('Outros')
MOBA <- base$genero_jogo %>% str_detect('MOBA')
SIM <- base$genero_jogo %>% str_detect('Simuladores')
ESPORTES <- base$genero_jogo %>% str_detect('Esportes')
ROYALE <- base$genero_jogo %>% str_detect('Battle Royale')

base$FPS <- ifelse(FPS,1,0)
base$RPG <- ifelse(RPG,1,0)
base$RTS <- ifelse(RTS,1,0)
base$LUTA <- ifelse(LUTA,1,0)
base$ACAO <- ifelse(ACAO,1,0)
base$PUZZ <- ifelse(PUZZ,1,0)
base$OUTROS <- ifelse(OUTROS,1,0)
base$MOBA <- ifelse(MOBA,1,0)
base$SIM <- ifelse(SIM,1,0)
base$ESPORTES <- ifelse(ESPORTES,1,0)
base$ROYALE <- ifelse(ROYALE,1,0)

summary(base1)